apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:sre2go/majestix.git'
    targetRevision: HEAD
    path: '/apps'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
