apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 6.11.1
    helm:
      releaseName: argocd
      valueFiles:
      - $values/apps/argocd.yaml
  - repoURL: https://argoproj.github.io/argo-helm
    targetRevision: main
    path: apps/argocd.yaml
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd