apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: git@github.com:sre2go/majestix.git
    chart: argo-cd
    targetRevision: 6.11.1
    helm:
      releaseName: argocd
      valueFiles:
      - $values/helm/argocd-values.yaml
  - repoURL: git@github.com:sre2go/majestix.git
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd