apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 6.11.1
    helm:
      releaseName: argocd
  destination:
    server: "https://argoproj.github.io/argo-helm"
    namespace: argocd