apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb-system
    targetRevision: 0.14.5
    helm:
      releaseName: metallb
      # valueFiles:
      # - $values/apps/metallb.yaml
  - repoURL: git@github.com:sre2go/majestix.git
    targetRevision: main
    path: crds/metallb.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
